version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    image: php:7-fpm
    volumes:
      - ./app:/app
    dockerfile: dockerfiles/Dockerfile.test	
  db:
   image: mysql
   environment:
      - MYSQL_DATABASE=milken
      - MYSQL_USER=milkenDev
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_PASSWORD=123
   ports:
      - "33061:3306"  
   volumes:
      - ./db_data:/var/lib/mysql
   restart: always

