version: '3.0'
services:
  web:
   image: nginx:latest
   container_name: milken-web-container
   ports:
    - "8080:80"
   volumes:
    - ./app:/app 
    - ./site.conf:/etc/nginx/conf.d/default.conf
   depends_on:
    - php
   links:
    - php

  php:
   build: 
    context: . 
    dockerfile: dockerfiles/Dockerfile
   container_name: milken-php-container
   volumes:
    - ./app:/app
   command: bash -c "/usr/local/bin/php_script.sh"
   stdin_open: true
   ports:
    - "9000:9000"
   depends_on:
    - db
   links:
    - db:mysql
   environment:
    - PHP_CONF_FILE=/etc/php5/fpm/conf.d/20-system.ini
    - PHP_CONF_FILE_CLI=/etc/php5/cli/conf.d/20-system.ini
    - PHP_CONF_TIMEZONE=Europe/Bucharest
    - PHP_CONF_MAX_EXECUTION_TIME=30
    - PHP_CONF_UPLOAD_LIMIT=40M
    - PHP_CONF_PHAR_READONLY=off
    - PHP_CONF_MEMORY_LIMIT=512M
    - PHP_CONF_DISPLAY_ERRORS=off
    - PHP_CONF_ERROR_REPORTING=0
    - PHP_POOL_FILE=/etc/php5/fpm/pool.d/20-system.pool.conf
    - PHP_POOL_PM_CONTROL=dynamic
    - PHP_POOL_PM_MAX_CHILDREN=20
    - PHP_POOL_PM_START_SERVERS=2
    - PHP_POOL_CATCH_WORKERS_OUTPUT=yes

  db:
   image: mysql
   container_name: milken-db-container
   environment:
    - MYSQL_DATABASE=milken
    - MYSQL_USER=milkenDev
    - MYSQL_ROOT_PASSWORD=123
    - MYSQL_PASSWORD=123
   ports:
    - "33061:3306"  
   volumes:
    - ./db_data:/var/lib/mysql
   restart: always

