version: '3.0'
services:
  web:
   image: nginx:latest
   ports:
    - "8080:80"
   volumes:
    - ./app:/app 
    - ./site.conf:/etc/nginx/conf.d/default.conf
   depends_on:
    - php

  php:
   build: 
    context: . 
    dockerfile: ./dockerfiles/Dockerfile
   volumes:
    - ./app:/app
   command: php-fpm
   stdin_open: true
   ports:
    - "9000:9000"

  db:
   image: mysql
   environment:
    - MYSQL_DATABASE=milken
    - MYSQL_USER=milkenDev
    - MYSQL_ROOT_PASSWORD=123
    - MYSQL_PASSWORD=123
   ports:
    - "33061:3306"  
   volumes:
    - ./db_data:/var/lib/mysql
   restart: always

