FROM php:7-fpm 

RUN apt-get update && apt-get install -y \
	curl \
	git \
	wget \
        zip

RUN php -r "copy('https://getcomposer.org/installer','composer-setup.php');" && \
    php composer-setup.php && \
    mv composer.pchar /usr/local/bin/composer

RUN composer create-project acquia/lightning-project /app

WORKDIR /app
